sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8
install: mvn clean install -f pom.xml -DskipTests=true
before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
script:
# Dirigible Version (latest | 3.2.5 | 3.3.0 | ...)
  - export RELEASE_VERSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`

# Image dirigiblelabs/dirigible-tomcat
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$RELEASE_VERSION
  - docker push $REPO:$RELEASE_VERSION

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=promartio/store
    - secure: "m7aHKn1zKrWKEDFJFJTJ/rlQXs/qIGqPFGo5L84bMtiwd8Bsqs4zpw5eADEjVujduxIja8UTpQVNVi2QN95JOJ8XAh8I7nnNSdcW5SoIBv2LrRgDKr9ifhCRUnOHc9isI5gw1WMKl/ejW/nKfsRwJ0NCbtgBq+V8XJLlvlaj1/yjUytvWA1jqcYMp4DsbWgcVXiAS3RDXPsWtjakI/JeepTNtKs89nfacXUT88a4eSUEl4Cos1Vi5FToTBpLOWYx6LxbXTaLDeNnmT3QNeWRt3x9B22LMidTs7ciPDWZ4MCceRoCd9AvmZJiqsUHasMJVGiF2RW7Iegp+qQDKnTr/+TaOMJyHs5zL7aBViqekO6TAS3kI61TJb6vksQCImFuS4ZU7lMx718HF1K22QdX/bnCZ+hrsEVn9goG8OufUcNmAb2nLZppOnjOpmQTHX85urj9BES/zN94dR4ICGWeesWKfcQrdtk52rdqJvEiUWR4kN9GUsVM+XqDHwqlZZPUQFG9+4MlUPIhblIIeFuaowplWROASdxoQ6hwIFgwv0pMzkh+i9sI8AiXaeEuWMQsiQ7vzACsR7HnzvaHOKZ4DNQtlgXBAkIlGh3022CJ4QWqAxbcq+E4cj3pCcvNA9Xm2MOQ4KaaC+F7QrkdBzTVFHhPTE9QT8Cw+LkqilT2dUc="
    - secure: "oRxkW5GMwUP7T8qMeaMZtVXRhbkmURKFrNhuMtdTsZXr2DhjtsUF3aZgTD2CZeD8V4kCM9K+J6lZ28Tme7VPMaFepiPL5rppu4zGRFsDX++V4so1sTASHZUei5pVDHvvCT0qigQ86C3n/li+lNWjqsxJFY6yUiE0ODAcLJ/WgCqFE5fMHonw2MkXTEnwue5G5r3wl7aBLoofyKd+wCTINK6JY1yN9QdoSHBC9TT1fG6FVXg6ceMQV0SRcEIDXvHuafgKblhn/0ExzAPhj677pO1oe/NeNX36rms1XKuwpVGqraD0Eyjil0BYyxZrEE+cxqvYsV3SNgfJlRmpRbVGVGfR7Z+nB0PAds7XxKG/jRjMhRO0nXPzZr7a0oT06YR+iDyUdkdCnDem26bXWk2rI+8Gmcjw73ImwDxYnDFL8AO0rXyI4G3lTiRcYjFbJ1pZXcpAvdEb+y+Iu/GETkyb9JHofd3y9v/X64jdhi00N0gQfphgH3LZT0iATjxPUaMU7IvpBOPUWxwo6CPW/HgeChnCFTTSaNFMT+Bqz5mQHez5Ymq5v7ummaNcWNjxpGHqu/yxNsX++PxA48ZbdnAmX+Ar5Bfzozt6QCi5/JdsI2j0VOmGaLzvqNsQ/ljk6JC2nlhvBJxums/cF7yGbz0cRCGxkZ/0tiKj9fbspn3wRUQ="